id = "denix-zed-theme"
name = "Denix zed-theme"
version = "0.0.2"
schema_version = 1
authors = ["Denis Salmanovich <denis.salmanovich@gmail.com>"]
description = "🐧 DeniX theme for Zed editor"
repository = "https://github.com/denix666/zed-theme"
